version: '3.1'

services:

  java:
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: weather
      POSTGRES_USER: weather
      POSTGRES_DB: weather

  adminer:
    image: adminer
    restart: always
    ports:
      - 1000:8080
    depends_on:
      - db
